//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NPD {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NPD() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.NPD", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average sales per SKU (Rs. in lakhs).
        /// </summary>
        internal static string AverageSales {
            get {
                return ResourceManager.GetString("AverageSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach.
        /// </summary>
        internal static string Button_Text_Attach {
            get {
                return ResourceManager.GetString("Button_Text_Attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Competitor Information of the Category.
        /// </summary>
        internal static string Button_Text_CompetitorInformation {
            get {
                return ResourceManager.GetString("Button_Text_CompetitorInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Cumulative Sales PRojection.
        /// </summary>
        internal static string Button_Text_CumulativeSales {
            get {
                return ResourceManager.GetString("Button_Text_CumulativeSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product Feature.
        /// </summary>
        internal static string Button_Text_ProductFeature {
            get {
                return ResourceManager.GetString("Button_Text_ProductFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Target RLP.
        /// </summary>
        internal static string Button_Text_TargetRLP {
            get {
                return ResourceManager.GetString("Button_Text_TargetRLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category sales in 12 months (Rs. in lakhs).
        /// </summary>
        internal static string CategorySales {
            get {
                return ResourceManager.GetString("CategorySales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current SKUs.
        /// </summary>
        internal static string CurrentSKUs {
            get {
                return ResourceManager.GetString("CurrentSKUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Group  is required..
        /// </summary>
        internal static string Error_AgeGroup {
            get {
                return ResourceManager.GetString("Error_AgeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment is required.
        /// </summary>
        internal static string Error_Approver1Attachment {
            get {
                return ResourceManager.GetString("Error_Approver1Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bajaj Brand  is required..
        /// </summary>
        internal static string Error_BajajBrand {
            get {
                return ResourceManager.GetString("Error_BajajBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand  is required..
        /// </summary>
        internal static string Error_Brand {
            get {
                return ResourceManager.GetString("Error_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Saliency is required and make sure it should be between 0 to 100..
        /// </summary>
        internal static string Error_BusinessSaliency {
            get {
                return ResourceManager.GetString("Error_BusinessSaliency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit is required..
        /// </summary>
        internal static string Error_BusinessUnit {
            get {
                return ResourceManager.GetString("Error_BusinessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels  is required..
        /// </summary>
        internal static string Error_Channels {
            get {
                return ResourceManager.GetString("Error_Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Year  is required..
        /// </summary>
        internal static string Error_CurrentYear {
            get {
                return ResourceManager.GetString("Error_CurrentYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired Throughput is required and make sure it should be between 0 to 100..
        /// </summary>
        internal static string Error_DesiredThroughput {
            get {
                return ResourceManager.GetString("Error_DesiredThroughput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Attachment is required..
        /// </summary>
        internal static string Error_FileNameList {
            get {
                return ResourceManager.GetString("Error_FileNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender is required..
        /// </summary>
        internal static string Error_Gender {
            get {
                return ResourceManager.GetString("Error_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Group  is required..
        /// </summary>
        internal static string Error_IncomeGroup {
            get {
                return ResourceManager.GetString("Error_IncomeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intended Launch Date  is required..
        /// </summary>
        internal static string Error_IntendedLaunchDate {
            get {
                return ResourceManager.GetString("Error_IntendedLaunchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Share  is required and make sure it should be between 0 to 100..
        /// </summary>
        internal static string Error_MarketShare {
            get {
                return ResourceManager.GetString("Error_MarketShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Year is required..
        /// </summary>
        internal static string Error_mktCurrentYear1 {
            get {
                return ResourceManager.GetString("Error_mktCurrentYear1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Year is required..
        /// </summary>
        internal static string Error_mktCurrentYear2 {
            get {
                return ResourceManager.GetString("Error_mktCurrentYear2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Year is required..
        /// </summary>
        internal static string Error_mktNextYear1 {
            get {
                return ResourceManager.GetString("Error_mktNextYear1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Year is required..
        /// </summary>
        internal static string Error_mktNextYear2 {
            get {
                return ResourceManager.GetString("Error_mktNextYear2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Year is required..
        /// </summary>
        internal static string Error_mktPreviousYear1 {
            get {
                return ResourceManager.GetString("Error_mktPreviousYear1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Year is required..
        /// </summary>
        internal static string Error_mktPreviousYear2 {
            get {
                return ResourceManager.GetString("Error_mktPreviousYear2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Year  is required..
        /// </summary>
        internal static string Error_NextYear {
            get {
                return ResourceManager.GetString("Error_NextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Channels  is required..
        /// </summary>
        internal static string Error_OtherChannels {
            get {
                return ResourceManager.GetString("Error_OtherChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods  is required..
        /// </summary>
        internal static string Error_Periods {
            get {
                return ResourceManager.GetString("Error_Periods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Year  is required..
        /// </summary>
        internal static string Error_PreviousYear {
            get {
                return ResourceManager.GetString("Error_PreviousYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category  is required..
        /// </summary>
        internal static string Error_ProductCategory {
            get {
                return ResourceManager.GetString("Error_ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Feature is required..
        /// </summary>
        internal static string Error_ProductFeature {
            get {
                return ResourceManager.GetString("Error_ProductFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Positioning  is required..
        /// </summary>
        internal static string Error_ProductPositioning {
            get {
                return ResourceManager.GetString("Error_ProductPositioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name  is required..
        /// </summary>
        internal static string Error_ProjectName {
            get {
                return ResourceManager.GetString("Error_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project No  is required..
        /// </summary>
        internal static string Error_ProjectNo {
            get {
                return ResourceManager.GetString("Error_ProjectNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Trigger  is required..
        /// </summary>
        internal static string Error_ProjectTrigger {
            get {
                return ResourceManager.GetString("Error_ProjectTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Type  is required..
        /// </summary>
        internal static string Error_ProjectType {
            get {
                return ResourceManager.GetString("Error_ProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Brand  is required..
        /// </summary>
        internal static string Error_ReferenceBrand {
            get {
                return ResourceManager.GetString("Error_ReferenceBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Brand and Model is required..
        /// </summary>
        internal static string Error_ReferenceBrandAndModel {
            get {
                return ResourceManager.GetString("Error_ReferenceBrandAndModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions  is required..
        /// </summary>
        internal static string Error_Regions {
            get {
                return ResourceManager.GetString("Error_Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requestor Comments  is required..
        /// </summary>
        internal static string Error_RequestorComments {
            get {
                return ResourceManager.GetString("Error_RequestorComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RLP  is required..
        /// </summary>
        internal static string Error_RLP {
            get {
                return ResourceManager.GetString("Error_RLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Value  is required..
        /// </summary>
        internal static string Error_SalesValue {
            get {
                return ResourceManager.GetString("Error_SalesValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Volume  is required..
        /// </summary>
        internal static string Error_SalesVolume {
            get {
                return ResourceManager.GetString("Error_SalesVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target RLP  is required..
        /// </summary>
        internal static string Error_TargetRLP {
            get {
                return ResourceManager.GetString("Error_TargetRLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Transfer Price is required..
        /// </summary>
        internal static string Error_TargetTransferPrice {
            get {
                return ResourceManager.GetString("Error_TargetTransferPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is required.
        /// </summary>
        internal static string Error_Value {
            get {
                return ResourceManager.GetString("Error_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Address is required..
        /// </summary>
        internal static string Error_VendorAddress {
            get {
                return ResourceManager.GetString("Error_VendorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Name is required..
        /// </summary>
        internal static string Error_VendorName {
            get {
                return ResourceManager.GetString("Error_VendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitor Information of the category.
        /// </summary>
        internal static string Form_Title_CompetitorInformation {
            get {
                return ResourceManager.GetString("Form_Title_CompetitorInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumulative Sales Projection.
        /// </summary>
        internal static string Form_Title_CumulativeSalesProjection {
            get {
                return ResourceManager.GetString("Form_Title_CumulativeSalesProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Information.
        /// </summary>
        internal static string Form_Title_MarketInformation {
            get {
                return ResourceManager.GetString("Form_Title_MarketInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Customers.
        /// </summary>
        internal static string Form_Title_TargetCustomer {
            get {
                return ResourceManager.GetString("Form_Title_TargetCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Saliency (%).
        /// </summary>
        internal static string Grid_CumulativeSalesProjection_Header_Label_BusinessSaliency {
            get {
                return ResourceManager.GetString("Grid_CumulativeSalesProjection_Header_Label_BusinessSaliency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired Throughtput (%).
        /// </summary>
        internal static string Grid_CumulativeSalesProjection_Header_Label_DesiredThroughput {
            get {
                return ResourceManager.GetString("Grid_CumulativeSalesProjection_Header_Label_DesiredThroughput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods.
        /// </summary>
        internal static string Grid_CumulativeSalesProjection_Header_Label_Periods {
            get {
                return ResourceManager.GetString("Grid_CumulativeSalesProjection_Header_Label_Periods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target RLP (In Rs.).
        /// </summary>
        internal static string Grid_CumulativeSalesProjection_Header_Label_TargetRLP {
            get {
                return ResourceManager.GetString("Grid_CumulativeSalesProjection_Header_Label_TargetRLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Transfer Price (In Rs.).
        /// </summary>
        internal static string Grid_CumulativeSalesProjection_Header_Label_TargetTransferPrice {
            get {
                return ResourceManager.GetString("Grid_CumulativeSalesProjection_Header_Label_TargetTransferPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value (Rs. in lakhs).
        /// </summary>
        internal static string Grid_CumulativeSalesProjection_Header_Label_Value {
            get {
                return ResourceManager.GetString("Grid_CumulativeSalesProjection_Header_Label_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string Grid_ProductCompetitor_Header_Label_Brand {
            get {
                return ResourceManager.GetString("Grid_ProductCompetitor_Header_Label_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Share (%).
        /// </summary>
        internal static string Grid_ProductCompetitor_Header_Label_MarketShare {
            get {
                return ResourceManager.GetString("Grid_ProductCompetitor_Header_Label_MarketShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RLP (In Rs.).
        /// </summary>
        internal static string Grid_ProductCompetitor_Header_Label_RLP {
            get {
                return ResourceManager.GetString("Grid_ProductCompetitor_Header_Label_RLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Value (Rs. in lakhs).
        /// </summary>
        internal static string Grid_ProductCompetitor_Header_Label_SalesValue {
            get {
                return ResourceManager.GetString("Grid_ProductCompetitor_Header_Label_SalesValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Volume (Qty).
        /// </summary>
        internal static string Grid_ProductCompetitor_Header_Label_SalesVolume {
            get {
                return ResourceManager.GetString("Grid_ProductCompetitor_Header_Label_SalesVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bajaj Brand.
        /// </summary>
        internal static string Grid_ProductFeature_Header_Label_BajajBrand {
            get {
                return ResourceManager.GetString("Grid_ProductFeature_Header_Label_BajajBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Feature (MOSCOW).
        /// </summary>
        internal static string Grid_ProductFeature_Header_Label_ProductFeature {
            get {
                return ResourceManager.GetString("Grid_ProductFeature_Header_Label_ProductFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Brand.
        /// </summary>
        internal static string Grid_ProductFeature_Header_Label_ReferenceBrand {
            get {
                return ResourceManager.GetString("Grid_ProductFeature_Header_Label_ReferenceBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data in  Cumulative Sales Projection.
        /// </summary>
        internal static string Grid_Text_NoCumulativeSalesProjection {
            get {
                return ResourceManager.GetString("Grid_Text_NoCumulativeSalesProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data in Competitor Information of the Category.
        /// </summary>
        internal static string Grid_Text_NoProductCompetitor {
            get {
                return ResourceManager.GetString("Grid_Text_NoProductCompetitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data in  Product Feature.
        /// </summary>
        internal static string Grid_Text_NoProductFeatureData {
            get {
                return ResourceManager.GetString("Grid_Text_NoProductFeatureData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data in  Target RLP.
        /// </summary>
        internal static string Grid_Text_NoTargetRLPData {
            get {
                return ResourceManager.GetString("Grid_Text_NoTargetRLPData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category Details.
        /// </summary>
        internal static string Grid_Title_ProductCategoryDetail {
            get {
                return ResourceManager.GetString("Grid_Title_ProductCategoryDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Feature.
        /// </summary>
        internal static string Grid_Title_ProductFeature {
            get {
                return ResourceManager.GetString("Grid_Title_ProductFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABS Admin Attachment:.
        /// </summary>
        internal static string Label_ABSAdminAttachment {
            get {
                return ResourceManager.GetString("Label_ABSAdminAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABS Admin Comments:.
        /// </summary>
        internal static string Label_ABSAdminComments {
            get {
                return ResourceManager.GetString("Label_ABSAdminComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Group.
        /// </summary>
        internal static string Label_AgeGroup {
            get {
                return ResourceManager.GetString("Label_AgeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver 1 Attachment:.
        /// </summary>
        internal static string Label_Approver1Attachment {
            get {
                return ResourceManager.GetString("Label_Approver1Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver 1 Comments:.
        /// </summary>
        internal static string Label_Approver1Comments {
            get {
                return ResourceManager.GetString("Label_Approver1Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver 2 Attachment:.
        /// </summary>
        internal static string Label_Approver2Attachment {
            get {
                return ResourceManager.GetString("Label_Approver2Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver 2 Comments:.
        /// </summary>
        internal static string Label_Approver2Comments {
            get {
                return ResourceManager.GetString("Label_Approver2Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver 3 Attachment:.
        /// </summary>
        internal static string Label_Approver3Attachment {
            get {
                return ResourceManager.GetString("Label_Approver3Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver 3 Comments:.
        /// </summary>
        internal static string Label_Approver3Comments {
            get {
                return ResourceManager.GetString("Label_Approver3Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bajaj Brand.
        /// </summary>
        internal static string Label_BajajBrand {
            get {
                return ResourceManager.GetString("Label_BajajBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Saliency (%).
        /// </summary>
        internal static string Label_BusinessSaliency {
            get {
                return ResourceManager.GetString("Label_BusinessSaliency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit:.
        /// </summary>
        internal static string Label_BusinessUnit {
            get {
                return ResourceManager.GetString("Label_BusinessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels:.
        /// </summary>
        internal static string Label_Channels {
            get {
                return ResourceManager.GetString("Label_Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments/Remarks:.
        /// </summary>
        internal static string Label_Comments {
            get {
                return ResourceManager.GetString("Label_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy From ID.
        /// </summary>
        internal static string Label_CopyFromID {
            get {
                return ResourceManager.GetString("Label_CopyFromID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired Throughtput (%).
        /// </summary>
        internal static string Label_DesiredThroughput {
            get {
                return ResourceManager.GetString("Label_DesiredThroughput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Make :.
        /// </summary>
        internal static string Label_DriverMake {
            get {
                return ResourceManager.GetString("Label_DriverMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal CRI :.
        /// </summary>
        internal static string Label_DriverNominalCRI {
            get {
                return ResourceManager.GetString("Label_DriverNominalCRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver output voltage (V) :.
        /// </summary>
        internal static string Label_DriverOutputVoltage {
            get {
                return ResourceManager.GetString("Label_DriverOutputVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Type (CVCC,CC,CV) :.
        /// </summary>
        internal static string Label_DriverType {
            get {
                return ResourceManager.GetString("Label_DriverType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Attachment.
        /// </summary>
        internal static string Label_FileNameList {
            get {
                return ResourceManager.GetString("Label_FileNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Label_Gender {
            get {
                return ResourceManager.GetString("Label_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Group.
        /// </summary>
        internal static string Label_IncomeGroup {
            get {
                return ResourceManager.GetString("Label_IncomeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intended Launch Date:.
        /// </summary>
        internal static string Label_IntendedLaunchDate {
            get {
                return ResourceManager.GetString("Label_IntendedLaunchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamp/LED Make :.
        /// </summary>
        internal static string Label_LampLEDMake {
            get {
                return ResourceManager.GetString("Label_LampLEDMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LED Bin :.
        /// </summary>
        internal static string Label_LEDBin {
            get {
                return ResourceManager.GetString("Label_LEDBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LED configuration (No. of LED in series and parallel) :.
        /// </summary>
        internal static string Label_LEDConfiguration {
            get {
                return ResourceManager.GetString("Label_LEDConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LED driving Current (A) :.
        /// </summary>
        internal static string Label_LEDDrivingCurrent {
            get {
                return ResourceManager.GetString("Label_LEDDrivingCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LED Part Number :.
        /// </summary>
        internal static string Label_LEDPartNumber {
            get {
                return ResourceManager.GetString("Label_LEDPartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Share (%).
        /// </summary>
        internal static string Label_MarketShare {
            get {
                return ResourceManager.GetString("Label_MarketShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal CCT :.
        /// </summary>
        internal static string Label_NominalCCT {
            get {
                return ResourceManager.GetString("Label_NominalCCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal CRI :.
        /// </summary>
        internal static string Label_NominalCRI {
            get {
                return ResourceManager.GetString("Label_NominalCRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.of lamp/LED :.
        /// </summary>
        internal static string Label_NoOfLampLED {
            get {
                return ResourceManager.GetString("Label_NoOfLampLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPD Attachments:.
        /// </summary>
        internal static string Label_NPDAttachment {
            get {
                return ResourceManager.GetString("Label_NPDAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old NPD Created Date:.
        /// </summary>
        internal static string Label_OldNPDCreatedDate {
            get {
                return ResourceManager.GetString("Label_OldNPDCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPD Rejected Date:.
        /// </summary>
        internal static string Label_OldNPDRejectedDate {
            get {
                return ResourceManager.GetString("Label_OldNPDRejectedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old NPD Project No:.
        /// </summary>
        internal static string Label_OldProjectNo {
            get {
                return ResourceManager.GetString("Label_OldProjectNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Channels:.
        /// </summary>
        internal static string Label_OtherChannels {
            get {
                return ResourceManager.GetString("Label_OtherChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods.
        /// </summary>
        internal static string Label_Periods {
            get {
                return ResourceManager.GetString("Label_Periods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments (If any) :.
        /// </summary>
        internal static string Label_PhotometricComment {
            get {
                return ResourceManager.GetString("Label_PhotometricComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category:.
        /// </summary>
        internal static string Label_ProductCategory {
            get {
                return ResourceManager.GetString("Label_ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Description (Material used, Finish, Casting, other) :.
        /// </summary>
        internal static string Label_ProductDescription {
            get {
                return ResourceManager.GetString("Label_ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Feature(MOSCOW).
        /// </summary>
        internal static string Label_ProductFeature {
            get {
                return ResourceManager.GetString("Label_ProductFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Positioning:.
        /// </summary>
        internal static string Label_ProductPositioning {
            get {
                return ResourceManager.GetString("Label_ProductPositioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name:.
        /// </summary>
        internal static string Label_ProjectName {
            get {
                return ResourceManager.GetString("Label_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project No:.
        /// </summary>
        internal static string Label_ProjectNo {
            get {
                return ResourceManager.GetString("Label_ProjectNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger of the Project:.
        /// </summary>
        internal static string Label_ProjectTrigger {
            get {
                return ResourceManager.GetString("Label_ProjectTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Type:.
        /// </summary>
        internal static string Label_ProjectType {
            get {
                return ResourceManager.GetString("Label_ProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed By:.
        /// </summary>
        internal static string Label_ProposedBy {
            get {
                return ResourceManager.GetString("Label_ProposedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose of Testing :.
        /// </summary>
        internal static string Label_PurposeOfTesting {
            get {
                return ResourceManager.GetString("Label_PurposeOfTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Brand.
        /// </summary>
        internal static string Label_ReferenceBrand {
            get {
                return ResourceManager.GetString("Label_ReferenceBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Brand and Model:.
        /// </summary>
        internal static string Label_ReferenceBrandAndModel {
            get {
                return ResourceManager.GetString("Label_ReferenceBrandAndModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions:.
        /// </summary>
        internal static string Label_Regions {
            get {
                return ResourceManager.GetString("Label_Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date:.
        /// </summary>
        internal static string Label_RequestDate {
            get {
                return ResourceManager.GetString("Label_RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments/Remarks:.
        /// </summary>
        internal static string Label_RequestorComments {
            get {
                return ResourceManager.GetString("Label_RequestorComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RLP (In Rs.).
        /// </summary>
        internal static string Label_RLP {
            get {
                return ResourceManager.GetString("Label_RLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Value (Rs. in lakhs).
        /// </summary>
        internal static string Label_SalesValue {
            get {
                return ResourceManager.GetString("Label_SalesValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Volume (Qty).
        /// </summary>
        internal static string Label_SalesVolume {
            get {
                return ResourceManager.GetString("Label_SalesVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Required:.
        /// </summary>
        internal static string Label_SampleRequired {
            get {
                return ResourceManager.GetString("Label_SampleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target RLP (In Rs.).
        /// </summary>
        internal static string Label_TargetRLP {
            get {
                return ResourceManager.GetString("Label_TargetRLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Transfer Price (In Rs.).
        /// </summary>
        internal static string Label_TargetTransferPrice {
            get {
                return ResourceManager.GetString("Label_TargetTransferPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of test sample (Lamp,Luminaire, LED chip, module, lens, other) :.
        /// </summary>
        internal static string Label_TestSample {
            get {
                return ResourceManager.GetString("Label_TestSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test specification(if any) :.
        /// </summary>
        internal static string Label_TestSpecification {
            get {
                return ResourceManager.GetString("Label_TestSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of identical test samples :.
        /// </summary>
        internal static string Label_TotalNoOfIdenticalTestSample {
            get {
                return ResourceManager.GetString("Label_TotalNoOfIdenticalTestSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Light Source (LED, OLED, FTL, CFL, Incandescent, other).
        /// </summary>
        internal static string Label_TypeOfLightSource {
            get {
                return ResourceManager.GetString("Label_TypeOfLightSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value (Rs. in lakhs).
        /// </summary>
        internal static string Label_Value {
            get {
                return ResourceManager.GetString("Label_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Address:.
        /// </summary>
        internal static string Label_VendorAddress {
            get {
                return ResourceManager.GetString("Label_VendorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Name:.
        /// </summary>
        internal static string Label_VendorName {
            get {
                return ResourceManager.GetString("Label_VendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Year.
        /// </summary>
        internal static string MarketInformation_CurrYear {
            get {
                return ResourceManager.GetString("MarketInformation_CurrYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth rate (%).
        /// </summary>
        internal static string MarketInformation_GrowthRate {
            get {
                return ResourceManager.GetString("MarketInformation_GrowthRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market info category.
        /// </summary>
        internal static string MarketInformation_Marketinfocategory {
            get {
                return ResourceManager.GetString("MarketInformation_Marketinfocategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Year (est.).
        /// </summary>
        internal static string MarketInformation_NextYear {
            get {
                return ResourceManager.GetString("MarketInformation_NextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Year.
        /// </summary>
        internal static string MarketInformation_PrevYear {
            get {
                return ResourceManager.GetString("MarketInformation_PrevYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size (Rs. in lakhs).
        /// </summary>
        internal static string MarketInformation_SizeOfINR {
            get {
                return ResourceManager.GetString("MarketInformation_SizeOfINR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phased out SKUs.
        /// </summary>
        internal static string PhasedoutSKUs {
            get {
                return ResourceManager.GetString("PhasedoutSKUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Cumulative Sales Projection.
        /// </summary>
        internal static string Popup_Title_AddCumulativeSalesProjection {
            get {
                return ResourceManager.GetString("Popup_Title_AddCumulativeSalesProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product Competitor Information of Category.
        /// </summary>
        internal static string Popup_Title_AddProductCompetitor {
            get {
                return ResourceManager.GetString("Popup_Title_AddProductCompetitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product Feature.
        /// </summary>
        internal static string Popup_Title_AddProductFeature {
            get {
                return ResourceManager.GetString("Popup_Title_AddProductFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Target RLP.
        /// </summary>
        internal static string Popup_Title_AddTargetRLP {
            get {
                return ResourceManager.GetString("Popup_Title_AddTargetRLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Cumulative Sales Projection.
        /// </summary>
        internal static string Popup_Title_EditCumulativeSalesProjection {
            get {
                return ResourceManager.GetString("Popup_Title_EditCumulativeSalesProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Product Competitor Information of Category.
        /// </summary>
        internal static string Popup_Title_EditProductCompetitor {
            get {
                return ResourceManager.GetString("Popup_Title_EditProductCompetitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Product Feature.
        /// </summary>
        internal static string Popup_Title_EditProductFeature {
            get {
                return ResourceManager.GetString("Popup_Title_EditProductFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Target RLP.
        /// </summary>
        internal static string Popup_Title_EditTargetRLP {
            get {
                return ResourceManager.GetString("Popup_Title_EditTargetRLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Details.
        /// </summary>
        internal static string ProductCategoryDetail_Header_CatgoryDetail {
            get {
                return ResourceManager.GetString("ProductCategoryDetail_Header_CatgoryDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        internal static string ProductCategoryDetail_Header_Value {
            get {
                return ResourceManager.GetString("ProductCategoryDetail_Header_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABS Admin Section.
        /// </summary>
        internal static string Section_Title_NPDABSAdminSection {
            get {
                return ResourceManager.GetString("Section_Title_NPDABSAdminSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPD Approver.
        /// </summary>
        internal static string Section_Title_NPDApprover1Section {
            get {
                return ResourceManager.GetString("Section_Title_NPDApprover1Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPD Approver.
        /// </summary>
        internal static string Section_Title_NPDApprover2Section {
            get {
                return ResourceManager.GetString("Section_Title_NPDApprover2Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPD Approver.
        /// </summary>
        internal static string Section_Title_NPDApprover3Section {
            get {
                return ResourceManager.GetString("Section_Title_NPDApprover3Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPD Detail Section.
        /// </summary>
        internal static string Section_Title_NPDDetailDocumentSection {
            get {
                return ResourceManager.GetString("Section_Title_NPDDetailDocumentSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPD  is approved successfully.
        /// </summary>
        internal static string Text_ApproveSuccess {
            get {
                return ResourceManager.GetString("Text_ApproveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPD is completed successfully.
        /// </summary>
        internal static string Text_CompletedSuccess {
            get {
                return ResourceManager.GetString("Text_CompletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPD completed successfully.
        /// </summary>
        internal static string Text_CompleteSuccess {
            get {
                return ResourceManager.GetString("Text_CompleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumulative Sales Projection has been Deleted..
        /// </summary>
        internal static string Text_CumulativeSalesProjectionDeleted {
            get {
                return ResourceManager.GetString("Text_CumulativeSalesProjectionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required to have atleast one cumulative sales projection of each type (6 months, 12 months, 24 months)..
        /// </summary>
        internal static string Text_CumulativeSalesProjectionRequired {
            get {
                return ResourceManager.GetString("Text_CumulativeSalesProjectionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumulative Sales Projection added successfully..
        /// </summary>
        internal static string Text_CumulativeSalesProjectionSave {
            get {
                return ResourceManager.GetString("Text_CumulativeSalesProjectionSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPD is hold successfully.
        /// </summary>
        internal static string Text_HoldSuccess {
            get {
                return ResourceManager.GetString("Text_HoldSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This NPD Project No is already in used, Kindly Select another NPD Project No..
        /// </summary>
        internal static string Text_IsNPDGenerated {
            get {
                return ResourceManager.GetString("Text_IsNPDGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Competitor information of category deleted successfully..
        /// </summary>
        internal static string Text_NPDProductCompetitorDeleted {
            get {
                return ResourceManager.GetString("Text_NPDProductCompetitorDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Competitor information of category added successfully..
        /// </summary>
        internal static string Text_NPDProductCompetitorSave {
            get {
                return ResourceManager.GetString("Text_NPDProductCompetitorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Feature added successfully..
        /// </summary>
        internal static string Text_NPDProductFeatureSave {
            get {
                return ResourceManager.GetString("Text_NPDProductFeatureSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target RLP deleted successfully..
        /// </summary>
        internal static string Text_NPDTargetRLPDeleted {
            get {
                return ResourceManager.GetString("Text_NPDTargetRLPDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target RLP added successfully..
        /// </summary>
        internal static string Text_NPDTargetRLPSave {
            get {
                return ResourceManager.GetString("Text_NPDTargetRLPSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Feature has been Deleted..
        /// </summary>
        internal static string Text_ProductFeatureDeleted {
            get {
                return ResourceManager.GetString("Text_ProductFeatureDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required to have atleast one product feature of each type (Should have, Must have)..
        /// </summary>
        internal static string Text_ProductFeatureRequired {
            get {
                return ResourceManager.GetString("Text_ProductFeatureRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPD rejected successfully.
        /// </summary>
        internal static string Text_RejectedSuccess {
            get {
                return ResourceManager.GetString("Text_RejectedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPD is resumed sucessfully.
        /// </summary>
        internal static string Text_ResumeSuccess {
            get {
                return ResourceManager.GetString("Text_ResumeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPD is sent back for rework.
        /// </summary>
        internal static string Text_ReworkSuccess {
            get {
                return ResourceManager.GetString("Text_ReworkSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPD save as draft successfully.
        /// </summary>
        internal static string Text_SaveDraftSuccess {
            get {
                return ResourceManager.GetString("Text_SaveDraftSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPD saved successfully.
        /// </summary>
        internal static string Text_SaveSuccess {
            get {
                return ResourceManager.GetString("Text_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPD is submitted successfully.
        /// </summary>
        internal static string Text_Success {
            get {
                return ResourceManager.GetString("Text_Success", resourceCulture);
            }
        }
    }
}
